### ISSUE TITLE
Crash when scraping

### ISSUE THREAD

**Issue by bigjools** [bohdan-s/SunGather#137]
I had a brief network blip earlier and then this appeared in the log:
```
2023-09-13 09:13:33 WARNING  Failed to get Timestamp from Inverter, using Local Time: 2023-09-13 09:13:33
Failed to get Timestamp from Inverter, using Local Time: 2023-09-13 09:13:33
Traceback (most recent call last):
  File "/files/src/SunGather/venv/lib/python3.8/site-packages/SungrowClient/SungrowClient.py", line 388, in scrape
    self.latest_scrape["year"],
KeyError: 'year'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "sungather.py", line 190, in <module>
    main()
  File "sungather.py", line 154, in main
    success = inverter.scrape()
  File "/files/src/SunGather/venv/lib/python3.8/site-packages/SungrowClient/SungrowClient.py", line 405, in scrape
    del self.latest_scrape["year"]
KeyError: 'year'

```

**Comment by bigjools** [comment]
I have a small fix for this just to catch and ignore the error since it's failing in the SungrowClient library.
