### ISSUE TITLE
SG10RS - Configured to use total_active_power but not configured to scrape this register

### ISSUE THREAD

**Issue by jkerekes99** [bohdan-s/SunGather#185]
Hi, apologies if this has been covered before, however, I haven't been able to find the answer searching.

My inverter is:
SG10RS with WiNet-S Dongle

I am using the Home Assistant Addon via the repo.
I am getting all the entities except for:
* Active Generation
* Active Export to Grid
* Active Import from Grid

The log shows the following:
2024-06-04 12:22:38 INFO     Loaded config: /share/SunGather/config.yaml
2024-06-04 12:22:39 INFO     Loaded registers: registers-sungrow.yaml
2024-06-04 12:22:39 INFO     Registers file version: 0.2.4
2024-06-04 12:22:42 ERROR    MQTT: Configured to use total_active_power but not configured to scrape this register
MQTT: Configured to use total_active_power but not configured to scrape this register

Not sure what I'm doing wrong, there is not much to configure in the addin and as I said the other entities are working well.

**Comment by bohdan-s** [comment]
Smart _meter needs true and level set to 2

**Comment by jkerekes99** [comment]
> Smart _meter needs true and level set to 2

Thanks for the quick reply.
I have this set already, I still get that error in the log and those entities are missing:
![CleanShot 2024-06-04 at 17 46 17](https://github.com/bohdan-s/SunGather/assets/38056916/0d555d71-fd01-4243-a932-9a887ee469fc)

I have a S100 smart meter.

**Comment by jkerekes99** [comment]
So I opened /share/SunGather/config.yaml and it is showing level: 1.
So it is NOT taking the "level" changes made in the addon configuration tab.

**Comment by hadimiqbal** [comment]
Any update on this , i have the same inverter but cannot get HA to show anything

**Comment by jkerekes99** [comment]
It is working for me, just not:

- Active Generation
- Active Export to Grid
- Active Import from Grid

![CleanShot 2024-06-19 at 10 09 27](https://github.com/bohdan-s/SunGather/assets/38056916/88bf190c-0a07-4e6b-b0fe-66cb68592ae1)

**Comment by hadimiqbal** [comment]
having said that, it just started when i moved the port back to 502
![image](https://github.com/bohdan-s/SunGather/assets/77441749/70e305f7-9ae2-44c8-b35a-c6684247c030)

**Comment by jkerekes99** [comment]
@hadimiqbal 
So you get entities I don't.
But your Inverter is a different model to mine.

My inverter is a SG10RS
Yours is a SG10RT.

**Comment by hadimiqbal** [comment]
Yeah its actually RS i was just trying different name if it made a difference

**Comment by jkerekes99** [comment]
> Yeah its actually RS i was just trying different name if it made a difference

Interesting, where did you change the model?
You are getting "Active Power" where I am not.

**Comment by hadimiqbal** [comment]
i did it in the UI but the YAML looks like this for now
![image](https://github.com/bohdan-s/SunGather/assets/77441749/e1c73f80-5bd9-416b-9c93-e7f97a7d1987)

**Comment by hadimiqbal** [comment]
its funny i am not seeing the ones you see, do you think it may take time ?

**Comment by hadimiqbal** [comment]
would you know how toi generate more than these 3
![image](https://github.com/bohdan-s/SunGather/assets/77441749/29c88308-724f-40e6-b4f9-7a9c01391c26)

**Comment by jkerekes99** [comment]
Not sure, I don't think so.
My entities appeared immediately.

Are you running the latest firmware on your inverter?
![06AF4468-2510-4AE8-8864-C9CD73BEF1A0_4_5005_c](https://github.com/bohdan-s/SunGather/assets/38056916/7b2d9f0a-59c8-4873-a8ec-376909d2f836)

![A218789A-4454-4745-8B0B-E8C76F008D91_1_201_a](https://github.com/bohdan-s/SunGather/assets/38056916/0a42e5d7-6386-48c4-8cf0-55fa881728be)

**Comment by jkerekes99** [comment]
> would you know how toi generate more than these 3

They just appeared after entering the IP address into the GUI config and hitting start.

**Comment by jkerekes99** [comment]
Ok, so I managed to get all the supported entities working:
![CleanShot 2024-06-23 at 17 51 05](https://github.com/bohdan-s/SunGather/assets/38056916/dc7204e9-f20b-424a-8b20-100ea6009b2c)

I had to however set:
level:3
in the config.yaml (via terminal, not via HA adding).

Setting to 2 does not work.

However the issue I am getting now is the log file is filled with errors trying to scrape the other unsupported entities:
`Traceback (most recent call last):
  File "/venv/lib/python3.12/site-packages/pymodbus/transaction.py", line 208, in execute
    self.client.framer.processIncomingPacket(response,
  File "/venv/lib/python3.12/site-packages/pymodbus/framer/socket_framer.py", line 153, in processIncomingPacket
    self._process(callback)
  File "/venv/lib/python3.12/site-packages/pymodbus/framer/socket_framer.py", line 175, in _process
    raise ModbusIOException("Unable to decode request")
pymodbus.exceptions.ModbusIOException: Modbus Error: [Input/Output] Unable to decode request
2024-06-23 17:47:56 WARNING  Modbus connection failed
Modbus connection failed
2024-06-23 17:47:58 ERROR    index out of range
index out of range
2024-06-23 17:47:58 ERROR    Modbus Error: [Input/Output] Unable to decode request
Traceback (most recent call last):
  File "/venv/lib/python3.12/site-packages/pymodbus/transaction.py", line 208, in execute
    self.client.framer.processIncomingPacket(response,
  File "/venv/lib/python3.12/site-packages/pymodbus/framer/socket_framer.py", line 153, in processIncomingPacket
    self._process(callback)
  File "/venv/lib/python3.12/site-packages/pymodbus/framer/socket_framer.py", line 175, in _process
    raise ModbusIOException("Unable to decode request")
pymodbus.exceptions.ModbusIOException: Modbus Error: [Input/Output] Unable to decode request
Modbus Error: [Input/Output] Unable to decode request
Traceback (most recent call last):
  File "/venv/lib/python3.12/site-packages/pymodbus/transaction.py", line 208, in execute
    self.client.framer.processIncomingPacket(response,
  File "/venv/lib/python3.12/site-packages/pymodbus/framer/socket_framer.py", line 153, in processIncomingPacket
    self._process(callback)
  File "/venv/lib/python3.12/site-packages/pymodbus/framer/socket_framer.py", line 175, in _process
    raise ModbusIOException("Unable to decode request")
pymodbus.exceptions.ModbusIOException: Modbus Error: [Input/Output] Unable to decode request`

Is there a way to be able to pick the entities/registers you want the addon to scrape? rather than just choosing a level?
Ideally, I would love level 2 to work on the SG10RS inverters, however it doesn't.

**Comment by mitch-1211** [comment]
Hi @jkerekes99, I am also using this add on with the SG10RS. I'm able to get the following sensors with level 3:


```
Sungrow SG10RS Active Export to Grid
sensor.sungrow_sg5rs_active_export_to_grid
MQTT
—
—

Sungrow SG10RS Active Generation
sensor.sungrow_sg5rs_active_generation
MQTT
—
—

Sungrow SG10RS Active Import from Grid
sensor.sungrow_sg5rs_active_import_from_grid
MQTT
—
—

Sungrow SG10RS Daily Export to Grid
sensor.sungrow_sg10rs_daily_export_to_grid
MQTT
—
—

Sungrow SG10RS Daily Generation
sensor.sungrow_sg10rs_daily_generation
MQTT
—
—

Sungrow SG10RS Daily Import from Grid
sensor.sungrow_sg10rs_daily_import_from_grid
MQTT
—
—

Sungrow SG10RS Last reset
sensor.sungrow_sg10rs_last_reset
MQTT
—
—

Sungrow SG10RS Load Power
sensor.sungrow_sg10rs_load_power
MQTT
—
—

Sungrow SG10RS Meter Power
sensor.sungrow_sg10rs_meter_power
MQTT
—
—

Sungrow SG10RS Power State
binary_sensor.sungrow_sg10rs_power_state
MQTT
—
—

Sungrow SG10RS Temperature
sensor.sungrow_sg10rs_temperature
MQTT
—
—

Sungrow SG10RS Total Export Energy
sensor.sungrow_sg5rs_total_export_energy
MQTT
—
—

Sungrow SG10RS Total Import Energy
sensor.sungrow_sg5rs_total_import_energy
MQTT
—
—

Sungrow SG10RS Total Power Yields
sensor.sungrow_sg5rs_total_power_yields
MQTT
```

No errors in log like you have. Can you share your config.yaml? (located under /share/SunGather/config.yaml)
