### ISSUE TITLE
Not detecting correct inverter parameters?

### ISSUE THREAD

**Issue by MarkGardiner** [bohdan-s/SunGather#7]
Apologies if this is something a bit silly, I haven't had much of a look into it myself. I have a SG5.0RT with the WiNet-S dongle. On a run I get:

> python3 sungather.py
> 2021-12-24 10:56:12 ERROR    Failed loading export: timed out
> 			     Please make sure mqtt.py exists in the exports folder
> 2021-12-24 10:56:22 ERROR    index out of range
> 2021-12-24 10:56:22 ERROR    Modbus Error: [Input/Output] Unable to decode request
> Traceback (most recent call last):
>   File "/home/..../.local/lib/python3.7/site-packages/pymodbus/transaction.py", line 210, in execute
>     request.unit_id)
>   File "/home/..../.local/lib/python3.7/site-packages/pymodbus/framer/socket_framer.py", line 153, in processIncomingPacket
>     self._process(callback)
>   File "/home/..../.local/lib/python3.7/site-packages/pymodbus/framer/socket_framer.py", line 175, in _process
>     raise ModbusIOException("Unable to decode request")
> pymodbus.exceptions.ModbusIOException: Modbus Error: [Input/Output] Unable to decode request
> 2021-12-24 10:56:22 WARNING  Modbus connection failed: Modbus Error: [Input/Output] Unable to decode request
> 2021-12-24 10:56:22 ERROR    index out of range
> 2021-12-24 10:56:22 ERROR    Modbus Error: [Input/Output] Unable to decode request

I have tried setting:
`connection: http`
`model: "SG5.0RT"`
and it seems to work:
> python3 sungather.py
> Publish HTTP
> Publish HTTP

**Comment by MarkGardiner** [comment]
Ok, it was just me being silly not setting it to use http as the connection method - I assumed it would auto detect that as well.

**Comment by MarkGardiner** [comment]
BTW thank you so much!
